
package view;

import controller.ControladorRequerimientosReto4;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.vo.AsesorPorCiudad;
import model.vo.CompraPorProveedor;
import model.vo.ProyectosCasaCampestre;

public class VentanaConstructora extends javax.swing.JFrame {

    public static final ControladorRequerimientosReto4 CONTROLADOR = new ControladorRequerimientosReto4();
    
    /**
     * Creates new form VentanaConstructora
     */
    public VentanaConstructora() {
        initComponents();
        
        try
        {
            SetAsesoresPorCiudadToTableModel();
            SetComprasPorProveedorToTableModel();
            SetProyectosCasaCampestreToTableModel();
            
        }
        catch (SQLException e)
        {
            
        }
    }
    
    private void SetAsesoresPorCiudadToTableModel() throws SQLException
    {
        ArrayList<AsesorPorCiudad> asesoresPorCiudad = CONTROLADOR.consultarRequerimiento_1();
        DefaultTableModel AsesoresPorCiudadModel = (DefaultTableModel) AsesorPorCiudadTable.getModel();
        
        for(AsesorPorCiudad asesor:asesoresPorCiudad) 
        {
            Object [] rowData = { asesor.GetIdLider(), asesor.GetNombre(), asesor.GetCiudadResidencia() };
            AsesoresPorCiudadModel.addRow(rowData);
        }
    }
    
    private void SetComprasPorProveedorToTableModel() throws SQLException 
    {
        ArrayList<CompraPorProveedor> comprasPorProveedor = CONTROLADOR.consultarRequerimiento_2();
        DefaultTableModel ComprasPorProveedorModel = (DefaultTableModel) ComprasPorProveedorTable.getModel();
        
        for(CompraPorProveedor compra:comprasPorProveedor)
        {
            Object [] rowData = { compra.GetIdCompra(), compra.GetProveedor(), compra.GetConstructora(), compra.GetBancoVinculado(), compra.GetCiudad() };
            ComprasPorProveedorModel.addRow(rowData);
        }
    }
    
    private void SetProyectosCasaCampestreToTableModel() throws SQLException
    {
        ArrayList<ProyectosCasaCampestre> proyectosCasaCampestre = CONTROLADOR.consultarRequerimiento_3();
        DefaultTableModel ProyectosCasaCampestreModel = (DefaultTableModel) ProyectosCasaCampestreTable.getModel();
        
        for(ProyectosCasaCampestre proyecto:proyectosCasaCampestre)
        {
            Object [] rowData = { proyecto.GetIdProyecto(), proyecto.GetConstructora(), proyecto.GetNumeroHabitaciones(), proyecto.GetCiudad() };
            ProyectosCasaCampestreModel.addRow(rowData);
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        AsesorPorCiudadTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        ComprasPorProveedorTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        ProyectosCasaCampestreTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Constructora Esctructurando");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        AsesorPorCiudadTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Líder", "Nombre", "Ciudad de residencia"
            }
        ));
        jScrollPane1.setViewportView(AsesorPorCiudadTable);

        jTabbedPane1.addTab("Asesor por Ciudad", jScrollPane1);

        ComprasPorProveedorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Compra", "Proveedor", "Constructora", "Banco", "Ciudad"
            }
        ));
        jScrollPane2.setViewportView(ComprasPorProveedorTable);

        jTabbedPane1.addTab("Compras por proveedor", jScrollPane2);

        ProyectosCasaCampestreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id proyecto", "Constructora", "Número de habitaciones", "Ciudad"
            }
        ));
        jScrollPane3.setViewportView(ProyectosCasaCampestreTable);

        jTabbedPane1.addTab("Proyectos casa campestre", jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConstructora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConstructora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConstructora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConstructora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConstructora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AsesorPorCiudadTable;
    private javax.swing.JTable ComprasPorProveedorTable;
    private javax.swing.JTable ProyectosCasaCampestreTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
